services:
  - name: cloud-app
    type: web
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    region: frankfurt
    plan: free
    repo: https://github.com/Davidzh123/render_4IABD2_cloud
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cloud-db
          property: connectionString


databases:
  - name: cloud-db
    plan: free
    region: frankfurt
    
